"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.HttpMethod = exports.patch = exports.post = exports.deleteR = exports.put = exports.get = exports.request = void 0;
const http_interceptor_1 = require("./utils/http_interceptor");
Object.defineProperty(exports, "deleteR", { enumerable: true, get: function () { return http_interceptor_1.deleteR; } });
Object.defineProperty(exports, "get", { enumerable: true, get: function () { return http_interceptor_1.get; } });
Object.defineProperty(exports, "HttpMethod", { enumerable: true, get: function () { return http_interceptor_1.HttpMethod; } });
Object.defineProperty(exports, "patch", { enumerable: true, get: function () { return http_interceptor_1.patch; } });
Object.defineProperty(exports, "post", { enumerable: true, get: function () { return http_interceptor_1.post; } });
Object.defineProperty(exports, "put", { enumerable: true, get: function () { return http_interceptor_1.put; } });
Object.defineProperty(exports, "request", { enumerable: true, get: function () { return http_interceptor_1.request; } });
